// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	MonitorMapConnections      = "connections"
	MonitorProgTraceTcpConnect = "trace_tcp_connect"
)

// LoadMonitor returns the embedded CollectionSpec for Monitor.
func LoadMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Monitor: %w", err)
	}

	return spec, err
}

// LoadMonitorObjects loads Monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MonitorObjects
//	*MonitorPrograms
//	*MonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMonitorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorSpecs struct {
	MonitorProgramSpecs
	MonitorMapSpecs
	MonitorVariableSpecs
}

// MonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorProgramSpecs struct {
	TraceTcpConnect *ebpf.ProgramSpec `ebpf:"trace_tcp_connect"`
}

// MonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorMapSpecs struct {
	Connections *ebpf.MapSpec `ebpf:"connections"`
}

// MonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorVariableSpecs struct {
}

// MonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorObjects struct {
	MonitorPrograms
	MonitorMaps
	MonitorVariables
}

func (o *MonitorObjects) Close() error {
	return _MonitorClose(
		&o.MonitorPrograms,
		&o.MonitorMaps,
	)
}

// MonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorMaps struct {
	Connections *ebpf.Map `ebpf:"connections"`
}

func (m *MonitorMaps) Close() error {
	return _MonitorClose(
		m.Connections,
	)
}

// MonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorVariables struct {
}

// MonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorPrograms struct {
	TraceTcpConnect *ebpf.Program `ebpf:"trace_tcp_connect"`
}

func (p *MonitorPrograms) Close() error {
	return _MonitorClose(
		p.TraceTcpConnect,
	)
}

func _MonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed monitor_bpfel.o
var _MonitorBytes []byte
